name: Tofu staging apply & tests

on:
  push:
    branches: [staging]

permissions:
  contents: write        # to open PR later
  pull-requests: write
  id-token: write        # if you use OIDC anywhere
  actions: read

defaults:
  run:
    working-directory: infra

jobs:
  apply-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.HCLOUD_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.HCLOUD_S3_SECRET_KEY }}
      AWS_DEFAULT_REGION: eu-central
      # Any staging-specific TF_VAR_* go here
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - name: Init (staging)
        run: tofu init
      - name: Apply (staging)
        run: tofu apply -auto-approve -input=false

  integration-tests:
    runs-on: ubuntu-latest
    needs: apply-staging
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          # your real tests/checks here
          echo "Running checks against staging..."
          # exit 1 to fail if any check fails

  open-pr-to-main:
    runs-on: ubuntu-latest
    needs: integration-tests
    if: ${{ success() }}   # only if tests passed
    steps:
      - uses: actions/checkout@v4
      - name: Open PR from staging -> main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: staging
          title: "Promote staging to main"
          body: |
            This PR promotes the current `staging` to `main` after successful apply and tests.
          draft: false
