name: Tofu format & validate
on:
  push:
jobs:
  fmt_validate:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.HCLOUD_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.HCLOUD_S3_SECRET_KEY }}
    defaults:
      run:
        working-directory: infra/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Opentofu
        uses: opentofu/setup-opentofu@v1

      - name: Tofu format
        run: tofu fmt -recursive -diff

      # Tofu init and validate only ever run in a single directory.
      # (SIDE-NOTE: tofu plan includes an implied validation check)
      # TODO: Get changed modules/directorys and run init and validate only on them.
      - name: Tofu init
        run: tofu init

      - name: Tofu validate
        run: tofu validate