name: Tofu format, validate & plan

on:
  pull_request:
    branches: [staging, main]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write    # to post sticky comments
  actions: read

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - run: tofu fmt -recursive

  validate:
    runs-on: ubuntu-latest
    needs: fmt
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.HCLOUD_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.HCLOUD_S3_SECRET_KEY }}
      AWS_DEFAULT_REGION: eu-central
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - name: Init
        run: tofu init
      - name: Validate
        run: tofu validate

  plan:
    runs-on: ubuntu-latest
    needs: validate
    if: ${{ success() }}   # only if fmt & validate passed
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.HCLOUD_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.HCLOUD_S3_SECRET_KEY }}
      AWS_DEFAULT_REGION: eu-central
    outputs:
      plan_path: plan.txt
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - name: Init
        run: tofu init
      - name: Plan
        id: plan
        run: |
          tofu plan -input=false -no-color -out=plan.tfplan
          tofu show -no-color plan.tfplan > plan.txt
      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-plan
          path: plan.txt
      - name: Post/Update sticky plan comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: tofu-plan
          recreate: true
          message: |
            ### OpenTofu plan
            <details><summary>Expand</summary>

            ```txt
            ${{ steps.plan.outputs.plan_path }}
            ```
            </details>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  report-failures:
    # If anything failed, leave a comment explaining it.
    runs-on: ubuntu-latest
    needs: [fmt, validate, plan]
    if: ${{ failure() }}
    steps:
      - name: Summarize failures
        uses: actions/github-script@v7
        with:
          script: |
            const failed = Object.entries(context.payload.workflow_run?.jobs ?? {})
            core.notice('This step just posts a comment; details are in job logs.');
          # post a simple sticky failure comment
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: tofu-plan
          message: |
            ❌ **OpenTofu checks failed.**  
            - `tofu fmt -check` or `tofu validate` did not pass, so no plan was posted.
            Please fix the errors in the job logs; this PR cannot be merged while checks are failing.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
